# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [24]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [25]:
# Import torch
import torch 

# Create random tensor
random_tensorA = torch.rand(7, 7)
print(random_tensorA, random_tensorA.shape)

tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
        [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]]) torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [26]:
# Create another random tensor
random_tensorB = torch.rand(1, 7)

# Perform matrix multiplication 
mul_tensor = random_tensorA.mul(random_tensorB.T)
print(mul_tensor, mul_tensor.shape)

tensor([[0.6167, 0.3974, 0.2069, 0.1488, 0.3211, 0.2592, 0.5196],
        [0.0322, 0.4281, 0.0476, 0.3897, 0.1824, 0.3342, 0.3067],
        [0.2891, 0.3293, 0.4883, 0.3489, 0.4248, 0.0628, 0.4751],
        [0.4275, 0.3986, 0.3620, 0.4731, 0.6101, 0.2473, 0.1409],
        [0.0404, 0.0211, 0.0800, 0.0273, 0.0252, 0.1007, 0.1035],
        [0.1842, 0.1366, 0.1439, 0.2435, 0.0109, 0.0302, 0.2972],
        [0.5163, 0.2444, 0.0545, 0.2669, 0.1389, 0.2593, 0.3869]]) torch.Size([7, 7])


torch.mul() performs element-wise multiplication.

The two tensors must either have exactly the same shape, or be broadcastable.

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [27]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensorA = torch.rand(7, 7)
random_tensorB = torch.rand(1, 7)

# Matrix multiply tensors
mul_tensor = random_tensorA @ random_tensorB.T
print(mul_tensor, mul_tensor.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


torch.matmul() is matrix multiplication.

The number of columns of the first tensor must equal the number of rows of the second tensor.

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [28]:
# Set random seed on the GPU
torch.mps.manual_seed(1234) # If there is cuda, torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [29]:
# Set random seed
torch.mps.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "mps"
print(device)

# Create two random tensors on GPU
rand1 = torch.rand(2, 3).to(device)
rand2 = torch.rand(2, 3).to(device)
print(rand1)
print(rand2)

mps
tensor([[0.5932, 0.1123, 0.1535],
        [0.2417, 0.7262, 0.7011]], device='mps:0')
tensor([[0.2038, 0.6511, 0.7745],
        [0.4369, 0.5191, 0.6159]], device='mps:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [30]:
# Perform matmul on tensor_A and tensor_B
# Three approaches
rand_mul = rand1.matmul(rand2.T)
print(rand_mul, rand_mul.shape)

rand_mul = rand1.mm(rand2.T)
print(rand_mul, rand_mul.shape)

rand_mul = rand1 @ rand2.T
print(rand_mul, rand_mul.shape)

tensor([[0.3129, 0.4120],
        [1.0651, 0.9143]], device='mps:0') torch.Size([2, 2])
tensor([[0.3129, 0.4120],
        [1.0651, 0.9143]], device='mps:0') torch.Size([2, 2])
tensor([[0.3129, 0.4120],
        [1.0651, 0.9143]], device='mps:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [31]:
# Find max
max_val = rand_mul.max()
print(max_val)

# Find min
min_val = rand_mul.min()
print(min_val)

tensor(1.0651, device='mps:0')
tensor(0.3129, device='mps:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [32]:
# Find arg max
max_index = rand_mul.argmax()
print(max_index)

# Find arg min
min_index = rand_mul.argmin()
print(min_index)

tensor(2, device='mps:0')
tensor(0, device='mps:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [33]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand1 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
rand2 = torch.squeeze(rand1)

# Print out tensors and their shapes
print(rand1, rand1.shape)
print(rand2, rand2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
