# Exercises

In [1]:
import torch

2. Create a random tensor with shape (7, 7).

In [2]:
rand_tensor = torch.rand(7, 7)
rand_tensor

tensor([[0.0874, 0.6409, 0.2361, 0.2644, 0.8471, 0.4342, 0.0558],
        [0.5318, 0.7146, 0.9199, 0.1949, 0.2496, 0.4290, 0.7581],
        [0.7812, 0.4620, 0.7343, 0.7251, 0.9394, 0.0058, 0.4458],
        [0.6487, 0.9292, 0.7096, 0.8148, 0.6497, 0.3633, 0.9121],
        [0.4303, 0.2463, 0.1684, 0.6194, 0.3699, 0.9323, 0.2736],
        [0.6848, 0.0012, 0.2947, 0.4199, 0.0727, 0.5634, 0.0361],
        [0.4868, 0.5777, 0.4076, 0.0520, 0.9726, 0.3872, 0.9068]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [4]:
rand_tensor_1 = rand_tensor
rand_tensor_2 = torch.rand(1, 7)
rand_tensor_2

tensor([[0.3197, 0.2530, 0.3755, 0.4355, 0.8603, 0.2332, 0.2063]])

In [5]:
rand_tensor_1.mm(rand_tensor_2.T)

tensor([[1.2354],
        [1.2523],
        [1.8596],
        [1.8956],
        [1.1250],
        [0.7141],
        [1.5916]])

In [28]:
rand_tensor_1 @ rand_tensor_2.T

tensor([[1.2354],
        [1.2523],
        [1.8596],
        [1.8956],
        [1.1250],
        [0.7141],
        [1.5916]])

4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [29]:
RAND_SEED = 0
torch.manual_seed(RAND_SEED)
rand_tensor_3 = torch.rand(7, 7)
rand_tensor_4 = torch.rand(1, 7)
rand_tensor_3.mm(rand_tensor_4.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [11]:
torch.mps.manual_seed(1234)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [30]:
torch.mps.manual_seed(1234)
rand_tensor_5 = torch.rand(2, 3)
rand_tensor_6 = torch.rand(2, 3)

In [17]:
device = "mps" if torch.backends.mps.is_available else "cpu"
device

'mps'

In [21]:
rand_tensor_5 = rand_tensor_5.to(device)
rand_tensor_6 = rand_tensor_6.to(device)

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [22]:
mul_tensor = rand_tensor_5.mm(rand_tensor_6.T)
mul_tensor

tensor([[0.8386, 0.5860],
        [1.0676, 0.5279]], device='mps:0')

In [23]:
mul_tensor.device

device(type='mps', index=0)

8. Find the maximum and minimum values of the output of 7.

In [25]:
max_value = mul_tensor.max()
min_value = mul_tensor.min()
max_value, min_value

(tensor(1.0676, device='mps:0'), tensor(0.5279, device='mps:0'))

9. Find the maximum and minimum index values of the output of 7.

In [ ]:
max_value_idx = mul_tensor.argmax() # Get the one-dimensional index of the largest value (order after flattening)
min_value_idx = mul_tensor.argmin() # Gets the one-dimensional index of the minimum value (order after flattening)
max_value_idx, min_value_idx

(tensor(2, device='mps:0'), tensor(3, device='mps:0'))

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [27]:
torch.manual_seed(7)
four_dim_tensor = torch.rand(1, 1, 1, 10)
squeezed_tensor = four_dim_tensor.squeeze()
print(four_dim_tensor.shape)
print(squeezed_tensor.shape)

torch.Size([1, 1, 1, 10])
torch.Size([10])
